/**
 * scout-ingestion-policy.ts
 *
 * Explicit policy for what Scout may ingest from a knowledge source directory.
 * This file is the single source of truth — do not embed allowlist/deny logic
 * inline in scanner code.
 *
 * Policy rationale:
 *   - Ingestion source = only structured knowledge artifacts, not tooling noise
 *   - Projection export = output artifacts generated by the runtime
 *   - No agent metadata, runtime artifacts, or OS noise may enter the graph
 */

// Exact-match allowlist by basename
export const SCOUT_KNOWLEDGE_ALLOWLIST = new Set([
  // Root-level knowledge surface
  "README.md",
  "source-map.md",
  "raw-notes.md",
  "normalized-claims.jsonl",
  "open-questions.md",
  "loop-status.md",
  "comparison-matrix.md",
  "opportunity-hypotheses.md",
  "non-opportunities.md",
  // 01-overview
  "domain-map.md",
  "platform-summary.md",
  // Domain files
  "api-endpoints.md",
  "approval-workflow.md",
  "data-export.md",
  "delivery-frequency.md",
  "email-campaign-guide.md",
  "email-template-editor.md",
  "hard-bounce-optout-list.md",
  "import-history.md",
  "opt-out-page.md",
  // Competitive-intel surface files
  "orgs.jsonl",
  "derived.jsonl",
  "appmasters.jsonl",
  "org-upsell-candidates.jsonl",
])

// Pattern allowlist: array of [pattern, testFn]
// pattern is a RegExp used as documentation; testFn does the actual matching
// Order matters: checked after exact allowlist, before deny.
const SCOUT_ALLOW_PATTERNS: Array<[RegExp, (name: string) => boolean]> = [
  // Sales-meeting analysis files: 01-timeline.md, 02-recurring-unsolved-problems.md, etc.
  [/^\d{2}-[a-z-]+\.md$/i, (name) => /^\d{2}-[a-z-]+\.md$/i.test(name)],
  // Competitive-intel derived data files: org-*.jsonl, org-channel-usage.csv, etc.
  [/^org-[a-z-]+\.jsonl$/i, (name) => /^org-[a-z-]+\.jsonl$/i.test(name)],
  [/^org-[a-z-]+\.csv$/i, (name) => /^org-[a-z-]+\.csv$/i.test(name)],
  [/^appmasters\.jsonl$/i, (name) => /^appmasters\.jsonl$/i.test(name)],
  [/^org-upsell-candidates\.jsonl$/i, (name) => /^org-upsell-candidates\.jsonl$/i.test(name)],
]

export const SCOUT_PATH_DENYLIST = new Set([
  // Agent/tooling noise
  ".claude",
  ".openclaw",
  // Package artifacts
  "node_modules",
  // Generated artifacts
  "screenshots",
  // Personal agent loops
  "Loop #",
])

/**
 * Returns true if the given file path (case-insensitive) is an allowed
 * knowledge artifact for Scout ingestion.
 *
 * Rules (evaluated in order):
 *   1. Filename (basename) exactly in the allowlist → accepted
 *   2. Filename matches a known pattern (numbered analysis files, etc.) → accepted
 *   3. Any path segment (except .openclaw at home-dir position) matching a deny-listed term → rejected
 *   4. Everything else → rejected
 *
 * Note on .openclaw: paths like /Users/jojo/.openclaw/workspace/project/... contain .openclaw
 * as the home directory. This is NOT denied. Only .openclaw that appears as a standalone
 * agent metadata dir (e.g., /project/.openclaw/some-meta) is denied.
 */
export function isAllowedScoutArtifact(filePath: string): boolean {
  const lower = filePath.toLowerCase()
  const pathSegments = lower.split(/[\\/]/).filter(Boolean)
  for (const deniedTerm of SCOUT_PATH_DENYLIST) {
    if (deniedTerm === ".openclaw") {
      // Allow .openclaw if it's the home directory (appears at index 2 in /Users/jojo/.openclaw/...)
      // but deny it if it's a standalone agent metadata dir deeper in the path
      const idx = pathSegments.indexOf(".openclaw")
      if (idx === -1) continue
      // Home dir position: /Users/<user>/.openclaw/<rest> (index 2 after /Users/<user>/)
      const isHomeDirPosition = idx === 2
      if (isHomeDirPosition) continue
      return false
    }
    if (pathSegments.includes(deniedTerm.toLowerCase())) {
      return false
    }
  }
  const name = filePath.split(/[\\/]/).pop() ?? ""
  if (SCOUT_KNOWLEDGE_ALLOWLIST.has(name)) return true
  // Pattern matching for numbered analysis files
  for (const [pattern, test] of SCOUT_ALLOW_PATTERNS) {
    if (test(name)) return true
  }
  return false
}
